// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsHrIemxawHQbEI8OQA5QRsYEkDIkawkg',
    appId: '1:165732920648:web:9eae7ca870e81cb2c0977d',
    messagingSenderId: '165732920648',
    projectId: 'app-iue-d3f71',
    authDomain: 'app-iue-d3f71.firebaseapp.com',
    databaseURL: 'https://app-iue-d3f71-default-rtdb.firebaseio.com',
    storageBucket: 'app-iue-d3f71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA052CPgs4A9CqfiNdwgV0jz5-i4z5S_Ro',
    appId: '1:165732920648:android:8cd8ff7e75842c58c0977d',
    messagingSenderId: '165732920648',
    projectId: 'app-iue-d3f71',
    databaseURL: 'https://app-iue-d3f71-default-rtdb.firebaseio.com',
    storageBucket: 'app-iue-d3f71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZa_hHfX130GhFEmA-uJ2PDuQAxF8czAA',
    appId: '1:165732920648:ios:1ff7a5904ade2eb2c0977d',
    messagingSenderId: '165732920648',
    projectId: 'app-iue-d3f71',
    databaseURL: 'https://app-iue-d3f71-default-rtdb.firebaseio.com',
    storageBucket: 'app-iue-d3f71.appspot.com',
    iosBundleId: 'com.example.appuenvigado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZa_hHfX130GhFEmA-uJ2PDuQAxF8czAA',
    appId: '1:165732920648:ios:1ff7a5904ade2eb2c0977d',
    messagingSenderId: '165732920648',
    projectId: 'app-iue-d3f71',
    databaseURL: 'https://app-iue-d3f71-default-rtdb.firebaseio.com',
    storageBucket: 'app-iue-d3f71.appspot.com',
    iosBundleId: 'com.example.appuenvigado',
  );
}
